name: snowlab
version: "1.0.0"
profile: snowlab

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  snowlab:
    silver:
      +schema: SILVER
      +materialized: view
    gold:
      +schema: GOLD
      +materialized: table
